### ISSUE TITLE
Fast

### ISSUE THREAD

**Issue by dhwhale** [engcang/ieee_uav_2022#5]
This paper refers to the section related to UAV control by Gao Fei's team at Zhejiang University.

**Comment by engcang** [comment]
As mentioned here - https://github.com/engcang/ieee_uav_2022#references

We used target motion prediction part of Fast Tracker from Fei Gao's team.

**Comment by dhwhale** [comment]
Thanks for the reply, I was just trying to find the principle of Bessel curve prediction, and I thought his work wasn't referenced elsewhere, so I went through all the related work on github, and your work also Very well.

**Comment by engcang** [comment]
@dhwhale 
If you are still interested in this system and want to see the English version (extended version) of this system,
Please refer to this video: https://youtu.be/pMfhb25DqDU
The conference paper will be published soon.
(FARO-Tracker: Fast and Robust Target Tracking System for UAVs in Urban Environment, 
International Conference on Robot Intelligence Technology and Applications)
